# Generated by Django 4.0.6 on 2022-07-14 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField(null=True)),
                ('zip_code', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
